# LLMProxy 默认配置文件

# 服务器配置
http_server:
  # 转发服务配置
  forwards:
    - name: to_mixgroup # 转发服务名称，用于请求时指定，在同一配置文件中必须唯一
      port: 3000 # 服务监听端口
      address: "0.0.0.0" # 服务监听地址
      # 指向的上游组名称
      upstream_group: "mixgroup" # 上游组名称，必须在 `upstream_groups` 中定义，否则将导致错误
      # IP 基础的速率限制配置 (可选)
      ratelimit:
        enabled: true # 是否启用速率限制 (默认: false)
        per_second: 100 # 每秒最大请求数
        burst: 200 # 允许的突发请求数
      # 连接超时配置 (可选, 未指定则使用默认值)
      timeout:
        connect: 10 # 连接超时时间 (秒)
        idle: 60 # 连接空闲超时时间 (秒)
    - name: openai_group # 转发服务名称，用于请求时指定，在同一配置文件中必须唯一
      port: 3001 # 服务监听端口
      address: "0.0.0.0" # 服务监听地址
      # 指向的上游组名称
      upstream_group: "openai" # 上游组名称，必须在 `upstream_groups` 中定义，否则将导致错误
      # IP 基础的速率限制配置 (可选)
      ratelimit:
        enabled: true # 是否启用速率限制 (默认: false)
        per_second: 100 # 每秒最大请求数
        burst: 200 # 允许的突发请求数
      # 连接超时配置 (可选, 未指定则使用默认值)
      timeout:
        connect: 10 # 连接超时时间 (秒)
  # 管理服务配置 (当前提供 /metrics 和 /health 接口，不设速率限制)
  admin:
    port: 9000 # 管理服务监听端口
    address: "0.0.0.0" # 管理服务监听地址
    # 连接超时配置 (可选, 未指定则使用默认值)
    timeout:
      connect: 10 # 连接超时时间 (秒)

# 上游服务定义
upstreams:
  # OpenAI API 定义
  - name: openai_primary # 上游服务名称，在同一配置文件中必须唯一
    url: "https://api.openai.com/v1" # 上游服务 URL
    auth:
      type: "bearer" # 认证类型. 可选: "bearer", "basic", "none". (默认: "none", 不添加认证信息)
      token: "YOUR_OPENAI_API_KEY" # 认证令牌
    headers: # HTTP 头部操作
      - op: insert # 操作类型: insert (如果头部不存在则插入)
        key: X-Proxy-Auth
        value: "LLMProxy"
      - op: remove # 操作类型: remove (如果头部存在则删除)
        key: xxx-header-to-delete
      - op: replace # 操作类型: replace (如果头部存在则替换，否则插入)
        key: xxx-header-to-replace
        value: "new-value"

  # Anthropic API 定义
  - name: anthropic_primary # 上游服务名称，在同一配置文件中必须唯一
    url: "https://api.anthropic.com" # 上游服务 URL
    auth:
      type: "bearer" # 认证类型. 可选: "bearer", "basic", "none". (默认: "none", 不添加认证信息)
      token: "YOUR_ANTHROPIC_API_KEY" # 认证令牌
    headers: # HTTP 头部操作
      - op: insert # 操作类型: insert (如果头部不存在则插入)
        key: X-Proxy-Auth
        value: "LLMProxy"
      - op: remove # 操作类型: remove (如果头部存在则删除)
        key: xxx-header-to-delete
      - op: replace # 操作类型: replace (如果头部存在则替换，否则插入)

  # 使用 Basic 认证的示例上游
  - name: basic_auth_example # 上游服务名称，在同一配置文件中必须唯一
    url: "https://example.com/api" # 上游服务 URL
  # 注意: 如果未指定 `auth` 字段, 则不添加任何认证信息。
  # 注意: 如果未指定 `headers` 字段, 则不对发送到上游的请求头进行修改。

# 上游组定义
upstream_groups:
  # 混合上游组
  - name: mixgroup # 上游组名称，在同一配置文件中必须唯一
    # 包含的上游服务列表 (至少一个)
    upstreams:
      - name: openai_primary
      - name: anthropic_primary
    # 负载均衡策略 (可选, 默认: "roundrobin")
    balance:
      strategy: "roundrobin" # 轮询 (roundrobin) 策略
    # HTTP 客户端配置 (可选, 未指定则使用默认值)
    http_client:
      agent: "LLMProxy/1.0" # User-Agent 头部值 (默认: "LLMProxy/1.0")
      keepalive: 60 # TCP Keepalive 时间 (秒), 范围: 0-600. 0 表示禁用. (默认: 60)
      # `stream_mode` 未指定时默认为 true.
      # 连接超时配置 (可选, 未指定则使用默认值)
      timeout:
        connect: 10 # 连接超时时间 (秒)
        request: 10 # 请求超时时间 (秒)
        idle: 60 # 连接空闲超时时间 (秒)
      # 请求重试配置 (可选, 未指定则使用默认值)
      retry:
        enabled: true # 是否启用重试 (默认: false)
        attempts: 3 # 最大重试次数
        initial: 500 # 初始重试间隔 (毫秒)
      proxy: # HTTP/HTTPS 代理配置 (可选, 默认不启用)
        enabled: false # 是否启用代理 (默认: false)
        url: "" # 代理 URL, 例如: http://username:password@proxy.example.com:8080

  # OpenAI 上游组
  - name: openai # 上游组名称，在同一配置文件中必须唯一
    # 包含的上游服务列表 (至少一个)
    upstreams:
      - name: openai_primary
        weight: 8 # 权重 (默认: 1), 仅在 "weighted_roundrobin" 策略下生效
      - name: openai_backup
        weight: 2 # 权重 (默认: 1), 仅在 "weighted_roundrobin" 策略下生效
    # 负载均衡策略 (可选, 默认: "roundrobin")
    balance:
      strategy: "weighted_roundrobin" # 加权轮询 (weighted_roundrobin) 策略
    # HTTP 客户端配置 (可选, 未指定则使用默认值)
    http_client:
      agent: "LLMProxy/1.0" # User-Agent 头部值 (默认: "LLMProxy/1.0")
      keepalive: 60 # TCP Keepalive 时间 (秒), 范围: 0-600. 0 表示禁用. (默认: 60)
      stream_mode: true # 是否启用流式传输 (默认: true). 为 true 时, `timeout.request` 配置将失效.
      # 连接超时配置 (可选, 未指定则使用默认值)
      timeout:
        connect: 10 # 连接超时时间 (秒)
        request: 10 # 请求超时时间 (秒), 在 stream_mode:true 时无效
        idle: 60 # 连接空闲超时时间 (秒)
      # 请求重试配置 (可选, 未指定则使用默认值)
      retry:
        enabled: true # 是否启用重试 (默认: false)
        attempts: 3 # 最大重试次数
        initial: 500 # 初始重试间隔 (毫秒)
      proxy: # HTTP/HTTPS 代理配置 (可选, 默认不启用)
        enabled: false # 是否启用代理 (默认: false)
        url: "" # 代理 URL, 例如: http://username:password@proxy.example.com:8080

  # Anthropic 上游组
  - name: anthropic # 上游组名称，在同一配置文件中必须唯一
    # 包含的上游服务列表 (至少一个)
    upstreams:
      - name: anthropic_primary
    # 负载均衡策略 (可选, 默认: "roundrobin")
    balance:
      strategy: "random" # 随机 (random) 策略
    # HTTP 客户端配置 (可选, 未指定则使用默认值)
    http_client:
      agent: "LLMProxy/1.0" # User-Agent 头部值 (默认: "LLMProxy/1.0")
      keepalive: 60 # TCP Keepalive 时间 (秒), 范围: 0-600. 0 表示禁用. (默认: 60)
      stream: true # 是否启用流式传输 (默认: true). 注意: 此配置项已被 `stream_mode` 替代，后续版本可能会移除。为 true 时, `timeout.request` 配置将失效.
      # 连接超时配置 (可选, 未指定则使用默认值)
      timeout:
        connect: 10 # 连接超时时间 (秒)
        request: 10 # 请求超时时间 (秒), 在 stream_mode:true (或旧版 stream:true) 时无效
        idle: 60 # 连接空闲超时时间 (秒)
      # 请求重试配置 (可选, 未指定则使用默认值)
      retry:
        enabled: true # 是否启用重试 (默认: false)
        attempts: 3 # 最大重试次数
        initial: 500 # 初始重试间隔 (毫秒)
      proxy: # HTTP/HTTPS 代理配置 (可选, 默认不启用)
        enabled: false # 是否启用代理 (默认: false)
        url: "" # 代理 URL, 例如: http://username:password@proxy.example.com:8080

