apiVersion: v1
kind: Service
metadata:
  name: llmproxy
  namespace: llmproxy
  labels:
    app: llmproxy
spec:
  type: ClusterIP
  ports:
    - name: to-mixgroup
      port: 3000
      targetPort: to-mixgroup
    - name: openai
      port: 3001
      targetPort: openai
    - name: admin
      port: 9000
      targetPort: admin
  selector:
    app: llmproxy
